'use strict';

module.exports = app => {
  const { router, controller } = app;
  router.all('/api/system/login', controller.system.login);
  router.all('/api/system/logout', controller.system.logout);
  router.all('/api/system/menu/route', controller.system.menusRoute);
  router.all('/api/common/index/console', controller.system.console);
  router.all('/api/common/index/config', controller.system.configInfo);
  router.all('/api/ai/config/detail', controller.ai.ai.configDetail);
  router.all('/api/ai/config/save', controller.ai.ai.configSave);
  router.all('/api/ai/assistant/detail', controller.ai.ai.assistantDetail);
  router.all('/api/ai/assistant/save', controller.ai.ai.assistantSave);
  router.all('/api/ai/assistant/test', controller.ai.ai.test);
  router.all('/api/ai/chat/completions', controller.ai.ai.chat);
  router.all('/api/ai/chat/completions/editor', controller.ai.ai.editorGenerate);

  // 部门管理
  router.all('/api/system/dept/list', controller.system.dept.deptList);
  router.all('/api/system/dept/add', controller.system.dept.deptAdd);
  router.all('/api/system/dept/detail', controller.system.dept.deptDetail);
  router.all('/api/system/dept/edit', controller.system.dept.deptEdit);
  router.all('/api/system/dept/del', controller.system.dept.deptDel);
  router.all('/api/system/dept/all', controller.system.dept.deptAll);

  // 岗位管理
  router.all('/api/system/post/list', controller.system.post.postList);
  router.all('/api/system/post/add', controller.system.post.postAdd);
  router.all('/api/system/post/detail', controller.system.post.postDetail);
  router.all('/api/system/post/edit', controller.system.post.postEdit);
  router.all('/api/system/post/del', controller.system.post.postDel);
  router.all('/api/system/post/all', controller.system.post.postAll);

  // 管理员
  router.all('/api/system/admin/list', controller.system.admin.adminList);
  router.all('/api/system/admin/self', controller.system.admin.self);
  router.all('/api/system/admin/add', controller.system.admin.add);
  router.all('/api/system/admin/detail', controller.system.admin.detail);
  router.all('/api/system/admin/edit', controller.system.admin.edit);
  router.all('/api/system/admin/upInfo', controller.system.admin.update);
  router.all('/api/system/admin/del', controller.system.admin.del);
  router.all('/api/system/admin/disable', controller.system.admin.disable);

  // 角色管理
  router.all('/api/system/role/all', controller.system.role.roleAll);
  router.all('/api/system/role/list', controller.system.role.roleList);
  router.all('/api/system/role/detail', controller.system.role.detail);
  router.all('/api/system/role/add', controller.system.role.add);
  router.all('/api/system/role/edit', controller.system.role.edit);
  router.all('/api/system/role/del', controller.system.role.del);

  // 菜单管理
  router.all('/api/system/menu/list', controller.system.menu.menuList);
  router.all('/api/system/menu/detail', controller.system.menu.menuDetail);
  router.all('/api/system/menu/add', controller.system.menu.menuAdd);
  router.all('/api/system/menu/edit', controller.system.menu.menuEdit);
  router.all('/api/system/menu/del', controller.system.menu.menuDel);
  router.all('/api/system/notice/list', controller.system.notice.list);
  router.all('/api/system/notice/read', controller.system.notice.read);

  // 素材管理
  router.all('/api/common/album/cateList', controller.common.album.cateList);
  router.all('/api/common/album/cateAdd', controller.common.album.cateAdd);
  router.all('/api/common/album/cateRename', controller.common.album.cateRename);
  router.all('/api/common/album/cateDel', controller.common.album.cateDel);
  router.all('/api/common/album/albumList', controller.common.album.albumList);
  router.all('/api/common/album/albumRename', controller.common.album.albumRename);
  router.all('/api/common/album/albumDel', controller.common.album.albumDel);
  router.all('/api/common/album/albumAdd', controller.common.album.albumAdd);
  router.all('/api/common/album/albumMove', controller.common.album.albumMove);

  // 上传
  router.all('/api/common/upload/image', controller.common.album.uploadImage);
  // 远程图片转存（用于编辑器粘贴公众号等外链图片时落到素材库）
  router.all('/api/common/upload/image/transfer', controller.common.album.transferImage);
  // 正文图片一键转存（服务端抽取图片并替换正文）
  router.all('/api/common/upload/image/transfer-content', controller.common.album.transferEditorContentImages);
  router.all('/api/common/upload/video', controller.common.album.uploadVideo);
  router.all('/api/common/upload/file', controller.common.album.uploadFile);

  // 网站信息
  router.all('/api/setting/website/detail', controller.setting.website.details);
  router.all('/api/setting/website/save', controller.setting.website.save);
  // 官网设置
  router.all('/api/setting/official/detail', controller.setting.official.details);
  router.all('/api/setting/official/save', controller.setting.official.save);
  // 支付配置
  router.all('/api/setting/payment/detail', controller.setting.payment.detail);
  router.all('/api/setting/payment/save', controller.setting.payment.save);
  // 用户设置
  router.all('/api/setting/user/detail', controller.setting.user.detail);
  router.all('/api/setting/user/save', controller.setting.user.save);
  router.all('/api/setting/user/email/detail', controller.setting.user.emailDetail);
  router.all('/api/setting/user/email/save', controller.setting.user.emailSave);
  router.all('/api/setting/user/sms/detail', controller.setting.user.smsDetail);
  router.all('/api/setting/user/sms/save', controller.setting.user.smsSave);
  router.all('/api/setting/user/vip/detail', controller.setting.user.vipDetail);
  router.all('/api/setting/user/vip/save', controller.setting.user.vipSave);
  router.all('/api/setting/search/detail', controller.setting.search.detail);
  router.all('/api/setting/search/detail/stats', controller.setting.search.stats);
  router.all('/api/setting/search/save', controller.setting.search.save);
  // 会员提醒设置
  router.all('/api/setting/vip/notice/detail', controller.setting.vipNotice.detail);
  router.all('/api/setting/vip/notice/save', controller.setting.vipNotice.save);
  // 通知设置
  router.all('/api/setting/notice/list', controller.setting.notice.list);
  router.all('/api/setting/notice/detail', controller.setting.notice.detail);
  router.all('/api/setting/notice/save', controller.setting.notice.save);

  // 自定义通知
  router.all('/api/message/custom/send', controller.message.customSend);

  router.all('/api/setting/copyright/detail', controller.setting.copyright.details);
  router.all('/api/setting/copyright/save', controller.setting.copyright.save);
  router.all('/api/setting/protocol/detail', controller.setting.protocol.details);
  router.all('/api/setting/protocol/save', controller.setting.protocol.save);
  router.all('/api/setting/storage/list', controller.setting.storage.list);
  router.all('/api/setting/storage/detail', controller.setting.storage.detail);
  router.all('/api/setting/storage/edit', controller.setting.storage.edit);
  router.all('/api/setting/storage/change', controller.setting.storage.change);
  router.all('/api/monitor/server', controller.monitor.monitor.server);
  router.all('/api/monitor/cache', controller.monitor.monitor.cache);

  router.all('/api/product/list', controller.product.product.list);
  router.all('/api/product/add', controller.product.product.add);
  router.all('/api/product/detail', controller.product.product.detail);
  router.all('/api/product/edit', controller.product.product.edit);
  router.all('/api/product/edit/ai/update-log', controller.product.product.aiUpdateLogDraft);
  router.all('/api/product/del', controller.product.product.del);
  router.all('/api/product/package/list', controller.product.package.list);
  router.all('/api/product/package/add', controller.product.package.add);
  router.all('/api/product/package/detail', controller.product.package.detail);
  router.all('/api/product/package/edit', controller.product.package.edit);
  router.all('/api/product/package/del', controller.product.package.del);
  router.all('/api/product/package/template/detail', controller.product.package.templateDetail);
  router.all('/api/product/package/template/save', controller.product.package.templateSave);
  router.all('/api/product/package/public', controller.product.package.publicList);
  router.all('/api/product/version/list', controller.product.version.list);
  router.all('/api/product/version/add', controller.product.version.add);
  router.all('/api/product/version/detail', controller.product.version.detail);
  router.all('/api/product/version/edit', controller.product.version.edit);
  router.all('/api/product/version/del', controller.product.version.del);
  router.all('/api/product/version/publish', controller.product.version.publish);
  router.all('/api/product/version/public', controller.product.version.publicList);
  router.all('/api/product/version/lists', controller.product.version.publicLists);

  // 用户管理
  router.all('/api/user/stats', controller.user.stats);
  router.all('/api/user/list', controller.user.list);
  router.all('/api/user/detail', controller.user.detail);
  router.all('/api/user/edit', controller.user.edit);
  router.all('/api/user/wallet/adjust', controller.user.walletAdjust);
  router.all('/api/user/group/list', controller.user.groupList);
  router.all('/api/user/group/add', controller.user.groupAdd);
  router.all('/api/user/group/edit', controller.user.groupEdit);
  router.all('/api/user/group/del', controller.user.groupDel);
  router.all('/api/user/tag/list', controller.user.tagList);
  router.all('/api/user/tag/add', controller.user.tagAdd);
  router.all('/api/user/tag/edit', controller.user.tagEdit);
  router.all('/api/user/tag/del', controller.user.tagDel);
  router.all('/api/user/tag/bind', controller.user.tagBind);
  router.all('/api/user/level/list', controller.user.levelList);
  router.all('/api/user/level/add', controller.user.levelAdd);
  router.all('/api/user/level/edit', controller.user.levelEdit);
  router.all('/api/user/level/del', controller.user.levelDel);

  // 财务管理
  router.all('/api/finance/wallet/flow/list', controller.finance.walletFlowList);
  router.all('/api/finance/invoice/list', controller.finance.invoiceList);
  router.all('/api/finance/invoice/update', controller.finance.invoiceUpdate);
  router.all('/api/finance/feedback/list', controller.finance.feedbackList);

  // 优惠券管理
  router.all('/api/coupon/list', controller.coupon.list);
  router.all('/api/coupon/detail', controller.coupon.detail);
  router.all('/api/coupon/add', controller.coupon.add);
  router.all('/api/coupon/edit', controller.coupon.edit);
  router.all('/api/coupon/del', controller.coupon.del);
  router.all('/api/coupon/grant', controller.coupon.grant);

  // 用户中心
  router.all('/api/user/index/stats', controller.user.indexStats);
  router.all('/api/user/register', controller.user.register);
  router.all('/api/user/login', controller.user.login);
  router.all('/api/user/profile', controller.user.profile);
  router.all('/api/user/profile/update', controller.user.updateProfile);
  router.all('/api/user/author/options', controller.user.authorOptions);
  router.all('/api/user/author/center/detail', controller.user.authorCenterDetail);
  router.all('/api/user/author/center/save', controller.user.authorCenterSave);
  router.all('/api/user/author/public/detail', controller.user.authorPublicDetail);
  router.all('/api/user/password/change', controller.user.changePassword);
  router.all('/api/user/order/list', controller.user.orderList);
  router.all('/api/user/license/list', controller.user.licenseList);
  router.all('/api/user/order/create', controller.user.createOrder);
  router.all('/api/user/orders', controller.user.orders);
  router.all('/api/user/orders/detail/:id', controller.user.orderDetail);
  router.all('/api/user/orders/cancel/:id', controller.user.cancelOrder);
  router.all('/api/user/orders/refund/:id', controller.user.refundOrder);
  router.all('/api/user/licenses', controller.user.licenses);
  router.all('/api/user/license/bind', controller.user.bindLicense);
  router.all('/api/user/license/change', controller.user.changeLicenseDomain);
  router.all('/api/user/license/query', controller.license.query);
  router.all('/api/search/config', controller.search.config);
  router.all('/api/search/hot', controller.search.hot);
  router.all('/api/search/track', controller.search.track);
  router.all('/api/user/messages', controller.user.messages);
  router.all('/api/user/messages/read', controller.user.readMessage);
  router.all('/api/user/wallet', controller.user.wallet);
  router.all('/api/user/wallet/flows', controller.user.walletFlows);
  router.all('/api/user/message/list', controller.user.messageList);
  router.all('/api/user/message/read', controller.user.messageRead);
  router.all('/api/user/message/delete', controller.user.messageDelete);
  router.all('/api/user/collect/list', controller.user.collectList);
  router.all('/api/user/collect/toggle', controller.user.collectToggle);
  router.all('/api/user/article/collect/list', controller.user.articleCollectList);
  router.all('/api/user/article/like/list', controller.user.articleLikeList);
  router.all('/api/user/address/list', controller.user.addressList);
  router.all('/api/user/address/edit', controller.user.addressEdit);
  router.all('/api/user/address/del', controller.user.addressDel);
  router.all('/api/user/login/log', controller.user.loginLog);
  router.all('/api/user/wallet/info', controller.user.walletInfo);
  router.all('/api/user/wallet/log', controller.user.walletLog);
  router.all('/api/wallet/recharge', controller.user.walletRecharge);
  router.all('/api/user/vip/info', controller.user.vipInfo);
  router.all('/api/user/vip/goods', controller.user.vipGoods);
  router.all('/api/vip/purchase', controller.user.vipPurchase);
  router.all('/api/user/send_code', controller.user.sendCode);
  router.all('/api/user/bind', controller.user.bindAccount);
  router.all('/api/user/unbind', controller.user.unbindAccount);
  router.all('/api/user/cancel', controller.user.cancelAccount);
  router.all('/api/user/coupon/list', controller.userCoupon.list);
  router.all('/api/user/coupon/my', controller.userCoupon.myList);
  router.all('/api/user/coupon/receive', controller.userCoupon.receive);
  router.all('/api/user/invoice/list', controller.user.invoiceList);
  router.all('/api/user/invoice/apply', controller.user.invoiceApply);
  router.all('/api/user/feedback/add', controller.user.feedbackAdd);

  // 订单与授权管理
  router.all('/api/order/list', controller.order.list);
  router.all('/api/order/detail', controller.order.detail);
  router.all('/api/order/detail/:id', controller.order.detail);
  router.all('/api/license/list', controller.license.list);
  router.all('/api/license/detail', controller.license.detail);
  router.all('/api/license/detail/:id', controller.license.detail);
  router.all('/api/license/disable', controller.license.disable);
  router.all('/api/license/replace_domain', controller.license.replaceDomain);
  router.all('/api/license/audit', controller.license.audit);
  router.all('/api/risk/dashboard', controller.risk.dashboard);

  // 支付回调与交付
  router.all('/api/payment/notify', controller.payment.notify);
  router.all('/api/delivery/download', controller.delivery.download);

  // 日志管理
  router.all('/api/system/log/operate', controller.system.log.operate);

  // 字典管理
  router.all('/api/setting/dict/type/list', controller.setting.dict.list);
  router.all('/api/setting/dict/type/all', controller.setting.dict.all);
  router.all('/api/setting/dict/type/add', controller.setting.dict.add);
  router.all('/api/setting/dict/type/detail', controller.setting.dict.detail);
  router.all('/api/setting/dict/type/edit', controller.setting.dict.edit);
  router.all('/api/setting/dict/type/del', controller.setting.dict.del);
  router.all('/api/setting/dict/data/list', controller.setting.dict.dataList);
  router.all('/api/setting/dict/data/all', controller.setting.dict.dataAll);
  router.all('/api/setting/dict/data/detail', controller.setting.dict.dataDetail);
  router.all('/api/setting/dict/data/add', controller.setting.dict.dataAdd);
  router.all('/api/setting/dict/data/edit', controller.setting.dict.dataEdit);
  router.all('/api/setting/dict/data/del', controller.setting.dict.dataDel);

  // 生成代码
  router.all('/api/gen/list', controller.gen.gen.list);
  router.all('/api/gen/db', controller.gen.gen.dbTables);
  router.all('/api/gen/importTable', controller.gen.gen.importTable);
  router.all('/api/gen/delTable', controller.gen.gen.delTable);
  router.all('/api/gen/syncTable', controller.gen.gen.syncTable);
  router.all('/api/gen/previewCode', controller.gen.gen.previewCode);
  router.all('/api/gen/downloadCode', controller.gen.gen.downloadCode);

  // 内容管理 - 文章
  router.all('/api/article/cate/list', controller.article.cateList);
  router.all('/api/article/cate/all', controller.article.cateAll);
  router.all('/api/article/cate/add', controller.article.cateAdd);
  router.all('/api/article/cate/edit', controller.article.cateEdit);
  router.all('/api/article/cate/del', controller.article.cateDel);
  router.all('/api/article/cate/detail', controller.article.cateDetail);
  router.all('/api/article/cate/change', controller.article.cateChange);
  router.all('/api/article/tag/list', controller.article.tagList);
  router.all('/api/article/tag/all', controller.article.tagAll);
  router.all('/api/article/tag/add', controller.article.tagAdd);
  router.all('/api/article/tag/edit', controller.article.tagEdit);
  router.all('/api/article/tag/del', controller.article.tagDel);
  router.all('/api/article/tag/detail', controller.article.tagDetail);
  router.all('/api/article/tag/change', controller.article.tagChange);
  router.all('/api/article/tag/batch/change', controller.article.tagBatchChange);
  router.all('/api/article/tag/batch/del', controller.article.tagBatchDel);
  router.all('/api/article/tag/merge', controller.article.tagMerge);
  router.all('/api/article/topic/list', controller.article.topicList);
  router.all('/api/article/topic/all', controller.article.topicAll);
  router.all('/api/article/topic/add', controller.article.topicAdd);
  router.all('/api/article/topic/edit', controller.article.topicEdit);
  router.all('/api/article/topic/del', controller.article.topicDel);
  router.all('/api/article/topic/detail', controller.article.topicDetail);
  router.all('/api/article/topic/change', controller.article.topicChange);

  router.all('/api/article/list', controller.article.list);
  router.all('/api/article/all', controller.article.all);
  router.all('/api/article/add', controller.article.add);
  router.all('/api/article/front/add', controller.article.frontAdd);
  router.all('/api/article/front/list', controller.article.frontList);
  router.all('/api/article/front/detail', controller.article.frontDetail);
  router.all('/api/article/front/edit', controller.article.frontEdit);
  router.all('/api/article/front/audit', controller.article.frontAudit);
  router.all('/api/article/front/audit/message/list', controller.article.frontAuditMessageList);
  router.all('/api/article/edit', controller.article.edit);
  router.all('/api/article/del', controller.article.del);
  router.all('/api/article/detail', controller.article.detail);
  router.all('/api/article/change', controller.article.change);
  router.all('/api/article/visit/incr', controller.article.visitIncr);
  router.all('/api/article/collect/list', controller.article.collectList);
  router.all('/api/article/collect/toggle', controller.article.collectToggle);
  router.all('/api/article/like/toggle', controller.article.likeToggle);
  router.all('/api/article/stats', controller.article.stats);
  router.all('/api/article/comment/list', controller.article.commentList);
  router.all('/api/article/comment/add', controller.article.commentAdd);
  router.all('/api/article/comment/like/toggle', controller.article.commentLikeToggle);
  router.all('/api/article/comment/report/add', controller.article.commentReportAdd);
  router.all('/api/article/comment/top/toggle', controller.article.commentTopToggle);
  router.all('/api/article/comment/manage/list', controller.article.commentManageList);
  router.all('/api/article/comment/manage/replies', controller.article.commentManageReplies);
  router.all('/api/article/comment/manage/change', controller.article.commentManageChange);
  router.all('/api/article/comment/manage/del', controller.article.commentManageDel);
  router.all('/api/article/comment/manage/batch/change', controller.article.commentManageBatchChange);
  router.all('/api/article/comment/manage/batch/del', controller.article.commentManageBatchDel);
  router.all('/api/article/comment/manage/sensitive/detail', controller.article.commentManageSensitiveDetail);
  router.all('/api/article/comment/manage/sensitive/save', controller.article.commentManageSensitiveSave);
  router.all('/api/article/comment/manage/report/list', controller.article.commentManageReportList);
  router.all('/api/article/comment/manage/report/handle', controller.article.commentManageReportHandle);
  router.all('/api/article/comment/manage/mute/list', controller.article.commentManageMuteList);
  router.all('/api/article/comment/manage/mute/add', controller.article.commentManageMuteAdd);
  router.all('/api/article/comment/manage/mute/del', controller.article.commentManageMuteDel);
  router.all('/api/article/import/wechat', controller.article.importWechat);

  // 装修管理
  router.all('/api/decorate/pages/detail', controller.decorate.pageDetail);
  router.all('/api/decorate/pages/save', controller.decorate.pageSave);
  router.all('/api/decorate/tabbar/detail', controller.decorate.tabbarDetail);
  router.all('/api/decorate/tabbar/save', controller.decorate.tabbarSave);
  router.all('/api/decorate/data/article', controller.decorate.articleData);
};
