// This file is created by egg-ts-helper@1.35.2
// Do not modify this file!!!!!!!!!
/* eslint-disable */

import 'egg';
type AnyClass = new (...args: any[]) => any;
type AnyFunc<T = any> = (...args: any[]) => T;
type CanExportFunc = AnyFunc<Promise<any>> | AnyFunc<IterableIterator<any>>;
type AutoInstanceType<T, U = T extends CanExportFunc ? T : T extends AnyFunc ? ReturnType<T> : T> = U extends AnyClass ? InstanceType<U> : U;
import ExportAlbum = require('../../../app/service/album');
import ExportArticle = require('../../../app/service/article');
import ExportAuthAdmin = require('../../../app/service/authAdmin');
import ExportAuthDept = require('../../../app/service/authDept');
import ExportAuthMenu = require('../../../app/service/authMenu');
import ExportAuthPost = require('../../../app/service/authPost');
import ExportAuthRole = require('../../../app/service/authRole');
import ExportCommon = require('../../../app/service/common');
import ExportCopyright = require('../../../app/service/copyright');
import ExportDict = require('../../../app/service/dict');
import ExportGen = require('../../../app/service/gen');
import ExportLog = require('../../../app/service/log');
import ExportProtocol = require('../../../app/service/protocol');
import ExportRedis = require('../../../app/service/redis');
import ExportStorage = require('../../../app/service/storage');
import ExportUpload = require('../../../app/service/upload');
import ExportUser = require('../../../app/service/user');
import ExportWebsite = require('../../../app/service/website');
import ExportUiedAiConfig = require('../../../app/service/uied/aiConfig');
import ExportUiedAiUsageLog = require('../../../app/service/uied/aiUsageLog');
import ExportUiedArticle = require('../../../app/service/uied/article');
import ExportUiedArticleCategory = require('../../../app/service/uied/articleCategory');
import ExportUiedArticleTag = require('../../../app/service/uied/articleTag');
import ExportUiedBanner = require('../../../app/service/uied/banner');
import ExportUiedCategory = require('../../../app/service/uied/category');
import ExportUiedComment = require('../../../app/service/uied/comment');
import ExportUiedCommercialSlot = require('../../../app/service/uied/commercialSlot');
import ExportUiedContributionIncentive = require('../../../app/service/uied/contributionIncentive');
import ExportUiedDailyHot = require('../../../app/service/uied/dailyHot');
import ExportUiedDeliveryInit = require('../../../app/service/uied/deliveryInit');
import ExportUiedExport = require('../../../app/service/uied/export');
import ExportUiedFaviconApi = require('../../../app/service/uied/faviconApi');
import ExportUiedFooter = require('../../../app/service/uied/footer');
import ExportUiedFriendLink = require('../../../app/service/uied/friendLink');
import ExportUiedFrontend = require('../../../app/service/uied/frontend');
import ExportUiedHotRecommendation = require('../../../app/service/uied/hotRecommendation');
import ExportUiedLicenseCenter = require('../../../app/service/uied/licenseCenter');
import ExportUiedMonitor = require('../../../app/service/uied/monitor');
import ExportUiedNavMenu = require('../../../app/service/uied/navMenu');
import ExportUiedOperationLog = require('../../../app/service/uied/operationLog');
import ExportUiedPage = require('../../../app/service/uied/page');
import ExportUiedRankBoard = require('../../../app/service/uied/rankBoard');
import ExportUiedSeoScraper = require('../../../app/service/uied/seoScraper');
import ExportUiedSetting = require('../../../app/service/uied/setting');
import ExportUiedSocialMedia = require('../../../app/service/uied/socialMedia');
import ExportUiedStatistics = require('../../../app/service/uied/statistics');
import ExportUiedSubmission = require('../../../app/service/uied/submission');
import ExportUiedTopicFactory = require('../../../app/service/uied/topicFactory');
import ExportUiedWebsite = require('../../../app/service/uied/website');
import ExportUiedWebsiteInteraction = require('../../../app/service/uied/websiteInteraction');
import ExportUiedWebsiteTag = require('../../../app/service/uied/websiteTag');
import ExportUiedWordpressConfig = require('../../../app/service/uied/wordpressConfig');

declare module 'egg' {
  interface IService {
    album: AutoInstanceType<typeof ExportAlbum>;
    article: AutoInstanceType<typeof ExportArticle>;
    authAdmin: AutoInstanceType<typeof ExportAuthAdmin>;
    authDept: AutoInstanceType<typeof ExportAuthDept>;
    authMenu: AutoInstanceType<typeof ExportAuthMenu>;
    authPost: AutoInstanceType<typeof ExportAuthPost>;
    authRole: AutoInstanceType<typeof ExportAuthRole>;
    common: AutoInstanceType<typeof ExportCommon>;
    copyright: AutoInstanceType<typeof ExportCopyright>;
    dict: AutoInstanceType<typeof ExportDict>;
    gen: AutoInstanceType<typeof ExportGen>;
    log: AutoInstanceType<typeof ExportLog>;
    protocol: AutoInstanceType<typeof ExportProtocol>;
    redis: AutoInstanceType<typeof ExportRedis>;
    storage: AutoInstanceType<typeof ExportStorage>;
    upload: AutoInstanceType<typeof ExportUpload>;
    user: AutoInstanceType<typeof ExportUser>;
    website: AutoInstanceType<typeof ExportWebsite>;
    uied: {
      aiConfig: AutoInstanceType<typeof ExportUiedAiConfig>;
      aiUsageLog: AutoInstanceType<typeof ExportUiedAiUsageLog>;
      article: AutoInstanceType<typeof ExportUiedArticle>;
      articleCategory: AutoInstanceType<typeof ExportUiedArticleCategory>;
      articleTag: AutoInstanceType<typeof ExportUiedArticleTag>;
      banner: AutoInstanceType<typeof ExportUiedBanner>;
      category: AutoInstanceType<typeof ExportUiedCategory>;
      comment: AutoInstanceType<typeof ExportUiedComment>;
      commercialSlot: AutoInstanceType<typeof ExportUiedCommercialSlot>;
      contributionIncentive: AutoInstanceType<typeof ExportUiedContributionIncentive>;
      dailyHot: AutoInstanceType<typeof ExportUiedDailyHot>;
      deliveryInit: AutoInstanceType<typeof ExportUiedDeliveryInit>;
      export: AutoInstanceType<typeof ExportUiedExport>;
      faviconApi: AutoInstanceType<typeof ExportUiedFaviconApi>;
      footer: AutoInstanceType<typeof ExportUiedFooter>;
      friendLink: AutoInstanceType<typeof ExportUiedFriendLink>;
      frontend: AutoInstanceType<typeof ExportUiedFrontend>;
      hotRecommendation: AutoInstanceType<typeof ExportUiedHotRecommendation>;
      licenseCenter: AutoInstanceType<typeof ExportUiedLicenseCenter>;
      monitor: AutoInstanceType<typeof ExportUiedMonitor>;
      navMenu: AutoInstanceType<typeof ExportUiedNavMenu>;
      operationLog: AutoInstanceType<typeof ExportUiedOperationLog>;
      page: AutoInstanceType<typeof ExportUiedPage>;
      rankBoard: AutoInstanceType<typeof ExportUiedRankBoard>;
      seoScraper: AutoInstanceType<typeof ExportUiedSeoScraper>;
      setting: AutoInstanceType<typeof ExportUiedSetting>;
      socialMedia: AutoInstanceType<typeof ExportUiedSocialMedia>;
      statistics: AutoInstanceType<typeof ExportUiedStatistics>;
      submission: AutoInstanceType<typeof ExportUiedSubmission>;
      topicFactory: AutoInstanceType<typeof ExportUiedTopicFactory>;
      website: AutoInstanceType<typeof ExportUiedWebsite>;
      websiteInteraction: AutoInstanceType<typeof ExportUiedWebsiteInteraction>;
      websiteTag: AutoInstanceType<typeof ExportUiedWebsiteTag>;
      wordpressConfig: AutoInstanceType<typeof ExportUiedWordpressConfig>;
    }
  }
}
