// This file is created by egg-ts-helper@1.35.2
// Do not modify this file!!!!!!!!!
/* eslint-disable */

import 'egg';
import ExportAlbum = require('../../../app/model/album');
import ExportAlbumCate = require('../../../app/model/albumCate');
import ExportArticle = require('../../../app/model/article');
import ExportArticleAuthorRel = require('../../../app/model/articleAuthorRel');
import ExportArticleCategory = require('../../../app/model/articleCategory');
import ExportArticleCollect = require('../../../app/model/articleCollect');
import ExportArticleComment = require('../../../app/model/articleComment');
import ExportArticleLike = require('../../../app/model/articleLike');
import ExportArticleTag = require('../../../app/model/articleTag');
import ExportArticleTagRel = require('../../../app/model/articleTagRel');
import ExportArticleTopic = require('../../../app/model/articleTopic');
import ExportArticleTopicRel = require('../../../app/model/articleTopicRel');
import ExportDecoratePage = require('../../../app/model/decoratePage');
import ExportDecorateTabbar = require('../../../app/model/decorateTabbar');
import ExportDictData = require('../../../app/model/dictData');
import ExportDictType = require('../../../app/model/dictType');
import ExportGenTable = require('../../../app/model/genTable');
import ExportGenTableColumn = require('../../../app/model/genTableColumn');
import ExportHotSearch = require('../../../app/model/hotSearch');
import ExportNoticeSetting = require('../../../app/model/noticeSetting');
import ExportOfficialReply = require('../../../app/model/officialReply');
import ExportSystemAuthAdmin = require('../../../app/model/systemAuthAdmin');
import ExportSystemAuthDept = require('../../../app/model/systemAuthDept');
import ExportSystemAuthMenu = require('../../../app/model/systemAuthMenu');
import ExportSystemAuthPerm = require('../../../app/model/systemAuthPerm');
import ExportSystemAuthPost = require('../../../app/model/systemAuthPost');
import ExportSystemAuthRole = require('../../../app/model/systemAuthRole');
import ExportSystemConfig = require('../../../app/model/systemConfig');
import ExportSystemLogLogin = require('../../../app/model/systemLogLogin');
import ExportSystemLogOperate = require('../../../app/model/systemLogOperate');
import ExportSystemLogSms = require('../../../app/model/systemLogSms');
import ExportUser = require('../../../app/model/user');
import ExportUserAuth = require('../../../app/model/userAuth');
import ExportUserAuthorProfile = require('../../../app/model/userAuthorProfile');
import ExportUserGroup = require('../../../app/model/userGroup');
import ExportUserIdentity = require('../../../app/model/userIdentity');
import ExportUserLevel = require('../../../app/model/userLevel');
import ExportUserMessage = require('../../../app/model/userMessage');
import ExportUserTag = require('../../../app/model/userTag');
import ExportUserTagRel = require('../../../app/model/userTagRel');
import ExportUiedAiConfig = require('../../../app/model/uied/aiConfig');
import ExportUiedAiUsageLog = require('../../../app/model/uied/aiUsageLog');
import ExportUiedArticle = require('../../../app/model/uied/article');
import ExportUiedArticleCategory = require('../../../app/model/uied/articleCategory');
import ExportUiedArticleTag = require('../../../app/model/uied/articleTag');
import ExportUiedArticleTagRelation = require('../../../app/model/uied/articleTagRelation');
import ExportUiedBanner = require('../../../app/model/uied/banner');
import ExportUiedCategory = require('../../../app/model/uied/category');
import ExportUiedFaviconApi = require('../../../app/model/uied/faviconApi');
import ExportUiedFooterGroup = require('../../../app/model/uied/footerGroup');
import ExportUiedFooterLink = require('../../../app/model/uied/footerLink');
import ExportUiedFriendLink = require('../../../app/model/uied/friendLink');
import ExportUiedHotRecommendation = require('../../../app/model/uied/hotRecommendation');
import ExportUiedMedia = require('../../../app/model/uied/media');
import ExportUiedNavMenu = require('../../../app/model/uied/navMenu');
import ExportUiedOperationLog = require('../../../app/model/uied/operationLog');
import ExportUiedPage = require('../../../app/model/uied/page');
import ExportUiedPageCategory = require('../../../app/model/uied/pageCategory');
import ExportUiedSiteInfo = require('../../../app/model/uied/siteInfo');
import ExportUiedSiteSetting = require('../../../app/model/uied/siteSetting');
import ExportUiedSocialMediaGroup = require('../../../app/model/uied/socialMediaGroup');
import ExportUiedSocialMediaItem = require('../../../app/model/uied/socialMediaItem');
import ExportUiedWebsite = require('../../../app/model/uied/website');

declare module 'egg' {
  interface IModel {
    Album: ReturnType<typeof ExportAlbum>;
    AlbumCate: ReturnType<typeof ExportAlbumCate>;
    Article: ReturnType<typeof ExportArticle>;
    ArticleAuthorRel: ReturnType<typeof ExportArticleAuthorRel>;
    ArticleCategory: ReturnType<typeof ExportArticleCategory>;
    ArticleCollect: ReturnType<typeof ExportArticleCollect>;
    ArticleComment: ReturnType<typeof ExportArticleComment>;
    ArticleLike: ReturnType<typeof ExportArticleLike>;
    ArticleTag: ReturnType<typeof ExportArticleTag>;
    ArticleTagRel: ReturnType<typeof ExportArticleTagRel>;
    ArticleTopic: ReturnType<typeof ExportArticleTopic>;
    ArticleTopicRel: ReturnType<typeof ExportArticleTopicRel>;
    DecoratePage: ReturnType<typeof ExportDecoratePage>;
    DecorateTabbar: ReturnType<typeof ExportDecorateTabbar>;
    DictData: ReturnType<typeof ExportDictData>;
    DictType: ReturnType<typeof ExportDictType>;
    GenTable: ReturnType<typeof ExportGenTable>;
    GenTableColumn: ReturnType<typeof ExportGenTableColumn>;
    HotSearch: ReturnType<typeof ExportHotSearch>;
    NoticeSetting: ReturnType<typeof ExportNoticeSetting>;
    OfficialReply: ReturnType<typeof ExportOfficialReply>;
    SystemAuthAdmin: ReturnType<typeof ExportSystemAuthAdmin>;
    SystemAuthDept: ReturnType<typeof ExportSystemAuthDept>;
    SystemAuthMenu: ReturnType<typeof ExportSystemAuthMenu>;
    SystemAuthPerm: ReturnType<typeof ExportSystemAuthPerm>;
    SystemAuthPost: ReturnType<typeof ExportSystemAuthPost>;
    SystemAuthRole: ReturnType<typeof ExportSystemAuthRole>;
    SystemConfig: ReturnType<typeof ExportSystemConfig>;
    SystemLogLogin: ReturnType<typeof ExportSystemLogLogin>;
    SystemLogOperate: ReturnType<typeof ExportSystemLogOperate>;
    SystemLogSms: ReturnType<typeof ExportSystemLogSms>;
    User: ReturnType<typeof ExportUser>;
    UserAuth: ReturnType<typeof ExportUserAuth>;
    UserAuthorProfile: ReturnType<typeof ExportUserAuthorProfile>;
    UserGroup: ReturnType<typeof ExportUserGroup>;
    UserIdentity: ReturnType<typeof ExportUserIdentity>;
    UserLevel: ReturnType<typeof ExportUserLevel>;
    UserMessage: ReturnType<typeof ExportUserMessage>;
    UserTag: ReturnType<typeof ExportUserTag>;
    UserTagRel: ReturnType<typeof ExportUserTagRel>;
    Uied: {
      AiConfig: ReturnType<typeof ExportUiedAiConfig>;
      AiUsageLog: ReturnType<typeof ExportUiedAiUsageLog>;
      Article: ReturnType<typeof ExportUiedArticle>;
      ArticleCategory: ReturnType<typeof ExportUiedArticleCategory>;
      ArticleTag: ReturnType<typeof ExportUiedArticleTag>;
      ArticleTagRelation: ReturnType<typeof ExportUiedArticleTagRelation>;
      Banner: ReturnType<typeof ExportUiedBanner>;
      Category: ReturnType<typeof ExportUiedCategory>;
      FaviconApi: ReturnType<typeof ExportUiedFaviconApi>;
      FooterGroup: ReturnType<typeof ExportUiedFooterGroup>;
      FooterLink: ReturnType<typeof ExportUiedFooterLink>;
      FriendLink: ReturnType<typeof ExportUiedFriendLink>;
      HotRecommendation: ReturnType<typeof ExportUiedHotRecommendation>;
      Media: ReturnType<typeof ExportUiedMedia>;
      NavMenu: ReturnType<typeof ExportUiedNavMenu>;
      OperationLog: ReturnType<typeof ExportUiedOperationLog>;
      Page: ReturnType<typeof ExportUiedPage>;
      PageCategory: ReturnType<typeof ExportUiedPageCategory>;
      SiteInfo: ReturnType<typeof ExportUiedSiteInfo>;
      SiteSetting: ReturnType<typeof ExportUiedSiteSetting>;
      SocialMediaGroup: ReturnType<typeof ExportUiedSocialMediaGroup>;
      SocialMediaItem: ReturnType<typeof ExportUiedSocialMediaItem>;
      Website: ReturnType<typeof ExportUiedWebsite>;
    }
  }
}
